name: 'Chocofi'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR","#define MIRYOKU_KLUDGE_TOPROWCOMBOS_LEFTPINKIE 2 3","#define MIRYOKU_KLUDGE_TOPROWCOMBOS_RIGHTPINKIE 8 9","#define MIRYOKU_KLUDGE_BOTTOMROWCOMBOS_LEFTPINKIE 26 27","#define MIRYOKU_KLUDGE_BOTTOMROWCOMBOS_RIGHTPINKIE 32 33"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y","CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
