name: 'Build Example mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y","CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16","CONFIG_ZMK_KEYBOARD_NAME=Chocofi"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
